// Using a more efficient Set data structure for word lookups
const englishWords = new Set([
  // Common 3-letter words
  "THE", "AND", "FOR", "ARE", "BUT", "NOT", "YOU", "ALL", "ANY", "CAN", "HAD", "HER", "WAS", "ONE", "OUR", "OUT", "DAY", "GET", "HAS", "HIM", "HIS", "HOW", "MAN", "NEW", "NOW", "OLD", "SEE", "TWO", "WAY", "WHO", "BOY", "DID", "ITS", "LET", "PUT", "SAY", "SHE", "TOO", "USE",
  "CAT", "DOG", "RAT", "BAT", "HAT", "MAT", "SAT", "EAT", "RUN", "FUN", "SUN", "MAP", "CAP", "LAP", "TAP", "BAG", "TAG", "WAG", "LEG", "PEG", "BED", "RED", "FED", "LED", "BOX", "FOX", "JAM", "RAM", "HAM", "DAM", "CAM", "PAM", "SAM", "JAR", "CAR", "TAR", "WAR", "FAR", "BAR",
  
  // Common 4-letter words
  "DOOR", "WORD", "PLAY", "GAME", "TIME", "LOVE", "LIFE", "HOME", "WORK", "BOOK", "FOOD", "RAIN", "SNOW", "WIND", "FIRE", "TREE", "BIRD", "FISH", "STAR", "MOON", "SHIP", "BOAT", "ROAD", "PATH", "MIND", "SOUL", "HAND", "FOOT", "HEAD", "FACE", "EYES", "NOSE", "EARS", "HAIR",
  "ABLE", "BABY", "BACK", "BALL", "BANK", "BASE", "BATH", "BEAR", "BEAT", "BEER", "BELL", "BELT", "BEND", "BIKE", "BIND", "BIRD", "BITE", "BLOW", "BLUE", "BOAT", "BODY", "BONE", "BOOK", "BORN", "BOTH", "BOWL", "BURN", "CAKE", "CALL", "CALM", "CAMP", "CARD", "CARE", "CASE",
  
  // Common 5-letter words
  "HOUSE", "MOUSE", "WATER", "EARTH", "SPACE", "LIGHT", "NIGHT", "SOUND", "MUSIC", "DANCE", "SMILE", "LAUGH", "HAPPY", "SUNNY", "CLOUD", "STORM", "BEACH", "OCEAN", "RIVER", "PLANT",
  "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT", "AFTER", "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIKE", "ALIVE", "ALLOW", "ALONE",
  
  // Common 6-letter words
  "ACCEPT", "ACCESS", "ACCORD", "ACROSS", "ACTION", "ACTIVE", "ACTUAL", "ADJUST", "ADVICE", "ADVISE", "AFFECT", "AFFORD", "AFRAID", "AGENCY", "AGENDA", "ALMOST", "ALWAYS", "AMOUNT", "ANIMAL", "ANNUAL",
  
  // Common 7-letter words
  "ACCOUNT", "ACHIEVE", "ADDRESS", "ADVANCE", "ADVISE", "AGAINST", "AIRPORT", "ALCOHOL", "ALLIANCE", "ALREADY", "ANALYSE", "ANCIENT", "ANOTHER", "ANXIETY", "ANXIOUS", "ANYBODY", "APOLOGY", "APPROVE", "ARRANGE", "ARRIVAL",
  
  // Common 8-letter or longer words
  "ABSOLUTE", "ACADEMIC", "ACCEPTED", "ACCIDENT", "ACCURATE", "ACHIEVED", "ACQUIRED", "ACTIVITY", "ACTUALLY", "ADDITION", "ADEQUATE", "ADJACENT", "ADJUSTED", "ADVANCED", "ADVISORY", "ADVOCATE", "AFFECTED", "AIRCRAFT", "ALLIANCE",
  "BEAUTIFUL", "BEGINNING", "BEHAVIOR", "BUILDING", "BUSINESS", "CALENDAR", "CAMPAIGN", "CAPACITY", "CARRYING", "CATEGORY", "CHAMPION", "CHEMICAL", "CHILDREN", "CIRCULAR", "CIVILIAN",
  "CLASSICAL", "CLEANING", "CLOTHING", "COLLAPSE", "COLONIAL", "COLORFUL", "COMPLETE", "COMPUTER", "CONCRETE", "CONFLICT", "CONFUSED", "CONGRESS", "CONSIDER", "CONSTANT", "CONSUMER",
  "CONTINUE", "CONTRACT", "CONTRARY", "CONTRAST", "CONVINCE", "CORRIDOR", "COVERAGE", "COVERING", "CREATION", "CREATIVE", "CRIMINAL", "CRITICAL", "CROSSING", "CULTURAL", "CURRENCY",
  "CUSTOMER", "DATABASE", "DAUGHTER", "DAYLIGHT", "DEADLINE", "DECIDING", "DECISION", "DECREASE", "DEFERRED", "DEFINITE", "DELICATE", "DELIVERY", "DESCRIBE", "DESIGNER", "DETAILED",
  "DIABETES", "DIALOGUE", "DIAMETER", "DIRECTLY", "DIRECTOR", "DISABLED", "DISASTER", "DISCOVER", "DISORDER", "DISTANCE", "DISTINCT", "DISTRICT", "DIVIDEND", "DIVISION", "DOCUMENT",
  "DOMESTIC", "DOMINANT", "DRINKING", "DURATION", "DYNAMICS", "EASTERN", "ECONOMY", "EDITION", "EDITOR", "EDUCATED", "EFFECTIVE", "EFFICIENT", "EIGHTEEN", "ELECTION", "ELECTRIC",
  "ELIGIBLE", "EMERGING", "EMPHASIS", "EMPLOYEE", "ENGINEER", "ENORMOUS", "ENTIRELY", "ENTRANCE", "ENVELOPE", "EQUALITY", "EQUATION", "ESTIMATE", "EVENING", "EVIDENCE", "EXCHANGE",
  "EXCITING", "EXERCISE", "EXPLICIT", "EXPOSURE", "EXTENDED", "EXTERNAL", "FACILITY", "FAMILIAR", "FEATURED", "FEEDBACK", "FESTIVAL", "FINISHED", "FIREWALL", "FLAGSHIP", "FLEXIBLE",
  "FLOATING", "FOOTBALL", "FOOTHILL", "FORECAST", "FOREMOST", "FORMERLY", "FOURTEEN", "FRACTION", "FRANKLIN", "FREQUENT", "FRIENDLY", "FRONTIER", "FUNCTION", "GENERATE", "GENEROUS",
  "GENOMICS", "GOODWILL", "GOVERNOR", "GRADUATE", "GRAPHICS", "GRATEFUL", "GUARDIAN", "GUIDANCE", "HANDLING", "HARDWARE", "HERITAGE", "HIGHLAND", "HISTORIC", "HOMELESS", "HOMEPAGE",
  "HOSPITAL", "HUMANITY", "IDENTIFY", "IDENTITY", "IDEOLOGY", "IMPERIAL", "INCIDENT", "INCLUDED", "INCREASE", "INDICATE", "INDIRECT", "INDUSTRY", "INFORMAL", "INFORMED", "INHERENT",
  "INITIATE", "INNOCENT", "INSPIRED", "INSTANCE", "INTEGRAL", "INTENDED", "INTERACT", "INTEREST", "INTERIOR", "INTERNAL", "INTERVAL", "INTIMATE", "INTRANET", "INVASION", "INVOLVED",
  "ISOLATED", "JUDGMENT", "JUDICIAL", "JUNCTION", "KEYBOARD", "LANDLORD", "LANGUAGE", "LAUGHTER", "LEARNING", "LEVERAGE", "LIABILITY", "LICENSED", "LIGHTING", "LIKEWISE", "LIMITING",
  "LITERARY", "LOCATION", "MAGAZINE", "MAGNETIC", "MAINTAIN", "MAJORITY", "MARGINAL", "MARRIAGE", "MATERIAL", "MATURITY", "MAXIMIZE", "MEANING", "MEASURED", "MEDICINE", "MEDIEVAL",
  "MEMORIAL", "MERCHANT", "MIDNIGHT", "MILITARY", "MINIMIZE", "MINISTER", "MINISTRY", "MINORITY", "MOBILITY", "MODELING", "MODERATE", "MOMENTUM", "MONETARY", "MOREOVER", "MORTGAGE",
  "MOUNTAIN", "MOUNTING", "MOVEMENT", "MULTIPLE", "NATIONAL", "NEGATIVE", "NINETEEN", "NORTHERN", "NOTEBOOK", "NUMEROUS", "OBSERVER", "OCCASION", "OFFERING", "OFFICIAL", "OFFSHORE",
  "OPERATOR", "OPPONENT", "OPPOSITE", "OPTIMISM", "OPTIONAL", "ORDINARY", "ORGANIZE", "ORIGINAL", "OVERCOME", "OVERHEAD", "OVERSEAS", "OVERVIEW", "PAINTING", "PARALLEL", "PARENTAL",
  "PATENTED", "PATIENCE", "PEACEFUL", "PERIODIC", "PERSONAL", "PERSUADE", "PETITION", "PHYSICAL", "PIPELINE", "PLATFORM", "PLEASANT", "PLEASURE", "POLITICS", "PORTABLE", "PORTRAIT",
  "POSITION", "POSITIVE", "POSSIBLE", "POWERFUL", "PRACTICE", "PRECIOUS", "PREGNANT", "PRESENCE", "PRESENT", "PRESERVE", "PRESSING", "PRESSURE", "PREVIOUS", "PRINCESS", "PRINTING",
  "PRIORITY", "PROBABLE", "PROBABLY", "PRODUCER", "PROFOUND", "PROGRESS", "PROJECT", "PROMISE", "PROMOTE", "PROSPECT", "PROTECT", "PROTOCOL", "PROVIDED", "PROVIDER", "PROVINCE",
  "PUBLICLY", "PURCHASE", "PURSUANT", "QUANTITY", "QUESTION", "RATIONAL", "REACTION", "RECEIVED", "RECEIVER", "RECOVERY", "REGIONAL", "REGISTER", "REGULATE", "REINFORCE", "REJECTED",
  "RELATION", "RELATIVE", "RELEVANT", "RELIABLE", "RELIANCE", "RELIGION", "REMEMBER", "RENOWNED", "REPEATED", "REPORTER", "REPUBLIC", "REQUIRED", "RESEARCH", "RESERVED", "RESIDENT",
  "RESOLVED", "RESOURCE", "RESPONSE", "RESTRICT", "REVISION", "RIGOROUS", "ROMANTIC", "SAMPLING", "SCENARIO", "SCHEDULE", "SCRUTINY", "SEASONAL", "SECONDLY", "SECURITY", "SENSIBLE",
  "SENTENCE", "SEPARATE", "SEQUENCE", "SERGEANT", "SHIPPING", "SHORTAGE", "SHOULDER", "SIMPLIFY", "SITUATED", "SLIGHTLY", "SOFTWARE", "SOLUTION", "SOMEBODY", "SOMEWHAT", "SOUTHERN",
  "SPEAKING", "SPECIFIC", "SPECTRUM", "SPORTING", "STANDARD", "STANDING", "STANDOUT", "STERLING", "STRAIGHT", "STRATEGY", "STRENGTH", "STRIKING", "STRUGGLE", "STUNNING", "SUBURBAN",
  "SUITABLE", "SUPERIOR", "SUPPOSED", "SURPRISE", "SURVIVAL", "SURVIVOR", "SUSPECTED", "SUSTAINED", "SWIMMING", "SYMBOLIC", "SYMPATHY", "SYNDROME", "TACTICAL", "TAILORED", "TAKEOVER",
  "TANGIBLE", "TAXATION", "TAXPAYER", "TEACHING", "TENDENCY", "TERMINAL", "TERRIBLE", "THINKING", "THIRTEEN", "THOROUGH", "THOUSAND", "TOGETHER", "TOMORROW", "TOUCHING", "TRACKING",
  "TRAINING", "TRANSFER", "TRANSIT", "TRAUMA", "TREASURE", "TREATING", "TREATY", "TREMBLING", "TRIANGLE", "TROPICAL", "TROUBLE", "TURNING", "TWELVE", "TWENTY", "ULTIMATE", "UMBRELLA",
  "UNIVERSE", "UNLOCKED", "UNSIGNED", "UNUSUAL", "UPCOMING", "UPDATING", "UPGRADE", "UPSCALE", "UPSTAIRS", "UPWARD", "URGENCY", "USABLE", "USAGE", "USEFUL", "UTILITY", "VACATION",
  "VACCINE", "VAGABOND", "VALIANT", "VALIDATE", "VALIDITY", "VALUABLE", "VALUATION", "VARIABLE", "VARIANCE", "VARIANT", "VARIETY", "VARIOUS", "VARYING", "VEHICLE", "VENTURE",
  "VERBAL", "VERDICT", "VERIFIED", "VERSION", "VERTICAL", "VETERAN", "VIABLE", "VIBRANT", "VICINITY", "VICTORY", "VIEWING", "VILLAGE", "VINTAGE", "VIRTUAL", "VISIBLE", "VISION",
  "VISITOR", "VISUAL", "VITAL", "VITAMIN", "VOCAL", "VOLUME", "VOYAGE", "WAITING", "WALKING", "WANTING", "WARNING", "WARRANT", "WARRIOR", "WASHING", "WATCHING", "WEALTHY", "WEAPON",
  "WEATHER", "WEBINAR", "WEBSITE", "WEDDING", "WEEKEND", "WELCOME", "WELFARE", "WESTERN", "WHATEVER", "WHENEVER", "WHEREAS", "WHETHER", "WHISPER", "WILLING", "WINNING", "WINTER",
  "WISDOM", "WITNESS", "WONDER", "WOODEN", "WORKING", "WORKOUT", "WORRIED", "WORTHY", "WRITING", "WRITTEN", "YEARLY", "YELLOW", "YIELDING", "YOUNGER", "YOURSELF", "YOUTH", "ZEALOUS",
  "ZOOLOGY"
]);

export const isValidWord = (word: string): boolean => {
  // Convert to uppercase for consistent comparison
  return word.length >= 3 && englishWords.has(word.toUpperCase());
};